import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function RichTextEditor({ block, onUpdate }) {
    const handleChange = (field, value) => {
        onUpdate({
            ...block,
            data: {
                ...block.data,
                [field]: value
            }
        });
    };
    return (_jsxs("div", { className: "p-6 space-y-4", children: [_jsx("h3", { className: "font-medium text-gray-900 mb-4", children: "Rich Text Settings" }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Content" }), _jsx("textarea", { rows: 6, value: block.data.content || '', onChange: (e) => handleChange('content', e.target.value), className: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500", placeholder: "Enter your text content..." })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Alignment" }), _jsxs("select", { value: block.data.alignment || 'left', onChange: (e) => handleChange('alignment', e.target.value), className: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500", children: [_jsx("option", { value: "left", children: "Left" }), _jsx("option", { value: "center", children: "Center" }), _jsx("option", { value: "right", children: "Right" }), _jsx("option", { value: "justify", children: "Justify" })] })] }), _jsxs("div", { className: "border-t border-gray-200 pt-4", children: [_jsx("h4", { className: "text-sm font-medium text-gray-700 mb-3", children: "Formatting Options" }), _jsxs("div", { className: "space-y-2", children: [_jsxs("label", { className: "flex items-center space-x-2", children: [_jsx("input", { type: "checkbox", checked: block.data.allowBold || false, onChange: (e) => handleChange('allowBold', e.target.checked), className: "rounded border-gray-300 text-blue-600 focus:ring-blue-500" }), _jsx("span", { className: "text-sm text-gray-700", children: "Allow Bold Text" })] }), _jsxs("label", { className: "flex items-center space-x-2", children: [_jsx("input", { type: "checkbox", checked: block.data.allowItalic || false, onChange: (e) => handleChange('allowItalic', e.target.checked), className: "rounded border-gray-300 text-blue-600 focus:ring-blue-500" }), _jsx("span", { className: "text-sm text-gray-700", children: "Allow Italic Text" })] }), _jsxs("label", { className: "flex items-center space-x-2", children: [_jsx("input", { type: "checkbox", checked: block.data.allowLinks || false, onChange: (e) => handleChange('allowLinks', e.target.checked), className: "rounded border-gray-300 text-blue-600 focus:ring-blue-500" }), _jsx("span", { className: "text-sm text-gray-700", children: "Allow Links" })] })] })] })] }));
}
