# Configuración para Cloudflare Pages (no Workers)
# Este archivo se mantiene por compatibilidad pero no se usa

name = "aigym-minimax-ezez"
compatibility_date = "2024-01-01"

[env.production]
name = "aigym-minimax-ezez-prod"